# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

i_am_a_sponsor: true
hide_published_with: true

# Appearance

theme: minimal
day_night: false
font: tslab

# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size: M

# SEO

site_type: Organization
local_business_type: 'Research Group'
org_name: 'Infrastructure Risk & Resilience Research Group'
description: ''

# Contact (edit or remove options as required)

email: 
#phone: 888 888 88 88
# address:
#   street: Skempton Building
#   city: London
#   region: 
#   postcode: 'SW7 2BU'
#   country: United Kingdom
#   country_code: GB
# coordinates:
#   latitude: '51.498186'
#   longitude: '-0.17592'
directions: <b> Department of Water & Climate Risk </b><br> Institute for Environmental Studies <br> Vrije Universiteit Amsterdam <br>  De Boelelaan 1111, 1081 HV
#office_hours:
#appointment_url: 
contact_links:
 - icon: envelope
   icon_pack: fas
   name: Email enquiries
   link: "mailto: elco.koks@vu.nl"
 - icon: twitter
   icon_pack: fab
   name: "@ElcoK"
   link: "https://twitter.com/ElcoK"

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: true
diagram: true
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: square
publications:
  date_format: '2006'
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-139517690-1'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
