[build]
  command = "hugo --gc --minify -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.84.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "https://www.tslab.org/*"
  to = "https://transport-systems.imperial.ac.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.tslab.org/*"
  to = "https://transport-systems.imperial.ac.uk/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://tslab.org"
  to = "http://transport-systems.imperial.ac.uk"
  status = 301
  force = true

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
